module.exports = {
  memberId: "field_26",
  "Received ballot": "field_50",
  "Member ID": "field_26",
  "Member Name": "field_25",
  Branch: "field_4",
  Branch_raw: "field_4_raw",
  Section: "field_24",
  Employer: "field_27",
  "Worksite Name": "field_29",
  "Department Name": "field_30",
  Address: "field_31",
  Address_raw: "field_31_raw",
  "Mail Allowed": "field_32",
  Mobile: "field_33",
  Mobile_raw: "field_33_raw",
  "SMS Allowed": "field_34",
  "Home Phone": "field_35",
  "Home Phone_raw": "field_35_raw",
  "Home Email": "field_36",
  "Home Email_raw": "field_36_raw",
  "Work Email": "field_37",
  "Work Email_raw": "field_37_raw",
  "Email Allowed": "field_38",
  "Member Status Name": "field_39",
  "Member Status Date": "field_28",
  "Member Status Reason Name": "field_40",
  Language: "field_41",
  Delegates: "field_42",
  Organisors: "field_43",
  Lead: "field_106",
  Tags: "field_45",
  "Voting Intention": "field_49",
  "Has Received Ballot Paper": "field_50",
  "Has Returned Ballot Paper to AEC": "field_51",
  "How did they vote": "field_52",
  "Central Field Campaign": "field_53",
  "Last Conversation Date": "field_54",
  Notes: "field_73",
  "Do not contact": "field_74",
  "Needs New Ballot": "field_184",
  "Wrong Number": "field_185",
  "New Ballot Issued": "field_193",
};
